module 

universe u v w

set_option inductive.autoPromoteIndices false -- we set this option so that inductive definitions are not automatically changed...
set_option linter.unusedVariables false

noncomputable section
-- In lean you cannot form a type without giving its introduction rules. If you try to do this you get the type with no elements.
inductive MyVoid : Type 

abbrev Pi (A:Type u) (B:A→Type u) : Type u := (x:A) → (B x) -- Dependent functions are inherent to Lean, defined in kernel. this is just a notation for them.

def MyId : {A:Type} → A→A:= λ x=>x -- we will use the built in definition of id, this is just a demonstration.
--#check (@id)

def MyComp : {A B C : Type} → (B→C) → (A→B) → (A → C):= λ g => λ f => (λ x => g (f x)) -- We will be using the infix notation `_∘_` when necessary, this is just an example.



-- abbrev HPi (A:Type u) (B:A→Type v) : Type (max u v) := (x:A) → (B x) -- Heterogeneous version of Pi, in which universe levels do not have to match. Using Pi is preferable. 


inductive DPair : (A:Type u) → (B : A → Type u) → Type (u + 1) where
  | pair : {A : Type u} → {B:A→ Type u} → (x:A) → B x → DPair A B -- defined on page 33 of `Intro to HoTT`
-- lean has a type `Sigma` that we will use, this is just a demonstration
 
-- inductive HDPair : (A:Type u) → (B : A → Type v) → Type ((max u v) + 1) where
--   | pair : {A : Type u} → {B:A→ Type v} → (x:A) → B x → HDPair A B -- heterogeneous version of DPair, in which universe levels do not need to match. Using DPair is prefferable.

public inductive BPath {A: Type u}  (a:A) : A → Type u where
  | refl : BPath a a
--#check BPath.rec -- based path induction automatically generated by Lean

notation:max lhs "=ₚₚ" rhs => BPath lhs rhs -- we use `a=ₚb` as notation for `Path a b`. the symbol is typed "=\_p\_p". Lean can automatically infer what `A` is because it knows the type of `a` and `b`.

public inductive Path {A: Type u} : A → A → Type u where
  | refl : (a:A)→ Path a a
--#check Path.rec -- path induction automatically generated by Lean

abbrev Path.rfl {A : Type u} {a : A} : Path a a := Path.refl a
#check Path.rfl

notation lhs:10 "=ₚ" rhs:10 => Path lhs rhs -- we use `a=ₚb` as notation for `Path a b`. the symbol is typed "=\_p". Lean can automatically infer what `A` is because it knows the type of `a` and `b`.


-- Let's figure out what exactly path induction does!
-- Thene are two types of path induction, Based and Unbased. Both are equivalent, so I will use Unbased path induction because I like it more. Also, it aligns with the motivation for path induction giver here : https://hott.github.io/book/hott-online-82-g578b85c.pdf#section.5.8

-- One version of based path induction is as follows: fix `A:Type u` and `a:A`.
-- Suppose I want a function of type 
--          `f : ((a b:A) → p : a =ₚ b → X)`,
-- where `X` is a fixed type. I can define `f` entirely by saying "given `a:A`, here is where `f a a (refl a)` goes." 

-- What if `f` is a dependent function, i.e., the type of the output depends on the inouts? Then we have something called a 'motive', which looks like this:
--         `motive : ((a b:A) → p: a =ₚ b → Type v)`
-- What if I want to "prove" something, and I need a predicate function? you fool! Proofs are just elements of a type, and predicate functions are just dependent functions! Let's do an example. We will prove transitivity of `Path`:
public
def Path.trans {A:Type u} {a b c : A} : (a =ₚ b)→ (b =ₚ c) → (a=ₚ c) := 
  let motive: (x y : A) → (x=ₚy) → Type u := λ x y : A ↦ λ _ : x =ₚ y ↦ ( (y =ₚ c)→(x =ₚ c) ) -- here we define our motive. If I have a path from x to y, then my goal is to get an element in the type of functions that input a path from y to c and output a path from x to c. 
  have base : (x:A) → (motive x x (Path.refl x)) := λ x : A ↦ @id (Path x c)  -- This is saying that, for all x, we have an element of (x=ₚ c)→(x=ₚ c) the identity function
  show ∀ pab : (a=ₚ b), (b=ₚc) → (a=ₚc) from @Path.rec _ motive base _ _ -- go back to the definition of Path.rec and see if you can understand what happened here.

notation:max lhs "⊚" rhs => Path.trans lhs rhs -- here we define the notation p ⊚ q to mean the path p concatenated with the path q. this is the same as in rijke's textbook. we use this weird sybol (written as \oo ) because ∘ is already taken by functions. we could overload the namespace but I dont want to. 

-- theorem reflComp {A : Type} {a b : Type} {p : a =ₚ b}: ((Path.refl a) ⊚ p) = p := rfl -- we use the built in type Eq for "definitional equality". Do not use this unless you absolutely have to!

-- similarly we can prove that equality is reflexive, that is:
def Path.symm {A:Type u} {a b : A} : (a=ₚ b) → (b=ₚa) := 
  let motive : (x y : A) → (x =ₚ y) → Type u := λ x y ↦ λ pxy ↦ y=ₚx 
  let base : (x:A) → (motive x x (Path.refl x)) := λ x:A ↦ Path.refl x
  show ∀ (pab : a=ₚ b), b=ₚa from @Path.rec _ motive base _ _
 
-- short for associator, not associative.
def Path.assoc {A : Type u} {a b c d: A} {p : a =ₚ b} {q : b =ₚ c}  {r : c=ₚ d} :  
((p ⊚ q) ⊚ r) =ₚ (p ⊚ (q ⊚ r)) := sorry


end
