prelude 
universe u v w

set_option inductive.autoPromoteIndices false -- we set this option so that inductive definitions are not automatically changed...
/--
The canonical universe-polymorphic type with just one element.
It should be used in contexts that require a type to be universe polymorphic, thus disallowing
`Unit`.
-/
inductive PUnit : Type u where
  /-- The only element of the universe-polymorphic unit type. -/
  | unit : PUnit

inductive Nat' : Type where
| zero : Nat'
| succ : Nat' → Nat'

-- In lean you cannot form a type without giving its introduction rules. If you try to do this you get the type with no elements.
inductive Void : Type 

abbrev Pi (A:Type u) (B:A→Type u) : Type u := (x:A) → (B x) -- Dependent functions are inherent to Lean, defined in kernel. this is just a notation for them.

abbrev HPi (A:Type u) (B:A→Type v) : Type (max u v) := (x:A) → (B x) -- Heterogeneous version of Pi, in which universe levels do not have to match. Using Pi is preferable. 

inductive DPair : (A:Type u) → (B : A → Type u) → Type (u + 1) where
  | pair : {A : Type u} → {B:A→ Type u} → (x:A) → B x → DPair A B -- defined on page 33 of `Intro to HoTT`



inductive Eq {A: Type u} : A → A → Type u where
  /-- `Eq.refl a : a = a` is reflexivity, the unique constructor of the
  equality type. See also `rfl`, which is usually used instead. -/
  | refl : (a : A) → Eq a a

#check Eq.rec -- path induction automatically generated by Lean

